[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm --filter vendure-backend build"]

[start]
cmd = "cd apps/vendure-backend && node dist/index.js"
