[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.install]
cmds = [
  "cd ../..",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "cd ../..",
  "pnpm --filter stalknspice-storefront build"
]

[start]
cmd = "cd apps/stalknspice-storefront && pnpm start"
